services:
  nats:
    image: nats:2.10.20-alpine3.20
    container_name: bridge_bus
    ports:
      - "4222:4222"
      - "8222:8222"
    command: --js --http_port 8222 --sd /data
    volumes:
      - /mnt/telegram-bridge/nats:/data

  postgres:
    image: postgres:17-alpine
    container_name: bridge_store
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: bridge
    volumes:
      - /mnt/telegram-bridge/postgresql:/var/lib/postgresql/data
