services:
  nats:
    image: nats:2.10.20-alpine3.20
    container_name: nats-broker
    ports:
      - "4222:4222"
      - "8222:8222"
    command: --js --http_port 8222 --sd /data
    volumes:
      - /mnt/nats:/data
